##
## to be run on a nodepool with 5 nodes, caching enabled, 5 minute idle time
##


resources:
  - name: cache_repo
    type: GitRepo
    configuration:
      gitProvider: johns_github
      path: trriplejay/jfrog_samples
      branches:
        include: ^master$


pipelines:
  - name: cache_timing
    configuration:
      nodePool: test-short-cache
    steps:
      - name: starter
        type: Bash
        configuration:
          inputResources:
            - name: cache_repo

        execution:
          onExecute:
            - echo "Hello, here we go!"
      - name: p1
        type: Bash
        configuration:
          inputSteps:
            - name: starter
        execution:
          onExecute:
            - sleep 60
      - name: p2
        type: Bash
        configuration:
          inputSteps:
            - name: starter
        execution:
          onExecute:
            - sleep 60
      # - name: p3
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: starter
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: p4
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: starter
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: p5
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: starter
      #   execution:
      #     onExecute:
      #       - sleep 60

      - name: serial_1
        type: Bash
        configuration:
          inputSteps:
            - name: p1
            - name: p2
            # - name: p3
            # - name: p4
            # - name: p5
        execution:
          onExecute:
            - sleep 60
      - name: serial_2
        type: Bash
        configuration:
          inputSteps:
            - name: serial_1
        execution:
          onExecute:
            - sleep 60
      - name: serial_3
        type: Bash
        configuration:
          inputSteps:
            - name: serial_2
        execution:
          onExecute:
            - sleep 60
      - name: serial_4
        type: Bash
        configuration:
          inputSteps:
            - name: serial_3
        execution:
          onExecute:
            - sleep 60
      - name: serial_5
        type: Bash
        configuration:
          inputSteps:
            - name: serial_4
        execution:
          onExecute:
            - sleep 60
      - name: serial_6
        type: Bash
        configuration:
          inputSteps:
            - name: serial_5
        execution:
          onExecute:
            - sleep 60
      - name: serial_7
        type: Bash
        configuration:
          inputSteps:
            - name: serial_6
        execution:
          onExecute:
            - sleep 60
      - name: serial_8
        type: Bash
        configuration:
          inputSteps:
            - name: serial_7
        execution:
          onExecute:
            - sleep 60
      - name: serial_9
        type: Bash
        configuration:
          inputSteps:
            - name: serial_8
        execution:
          onExecute:
            - sleep 60
      # - name: serial_1B
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: p1
      #       - name: p2
      #       - name: p3
      #       - name: p4
      #       - name: p5
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: serial_2B
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: serial_1B
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: serial_3B
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: serial_2B
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: serial_4B
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: serial_3B
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: serial_5B
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: serial_4B
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: serial_6B
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: serial_5B
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: serial_7B
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: serial_6B
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: serial_8B
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: serial_7B
      #   execution:
      #     onExecute:
      #       - sleep 60
      # - name: serial_9B
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: serial_8B
      #   execution:
      #     onExecute:
      #       - sleep 60








