resources:
  - name: myrepo
    type: GitRepo
    configuration:
      gitProvider: johns_github
      path: trriplejay/jfrog_samples
      branches:
        include: ^master$

pipelines:
  - name: powershell_example
    steps:
      - name: simple_step
        type: PowerShell
        configuration:
          inputResources:
            - name: myrepo
          nodePool: win-dyna-test
        execution:
          onExecute:
            - Write-Output "hello world!"
            - jfrog --version
      - name: host_step
        type: PowerShell
        configuration:
          inputResources:
            - name: myrepo
              trigger: false
          inputSteps:
            - name: simple_step
          runtime:
            type: host
          nodePool: win-dyna-default
        execution:
          onExecute:
            - get-childitem $env:PROGRAMDATA
            # - try { nssm status pipelines-seeker } catch { $_ }  azure only
            - try { nssm status pipelines-reqkick } catch { $_ }
            - try {  Get-WindowsOptionalFeature -Online } catch {$_}
            # - cat $env:PROGRAMDATA\jfrog\pipelines\seeker\pipelines-seeker.err azure only
            # - cat $env:PROGRAMDATA\jfrog\pipelines\seeker\pipelines-seeker.out azure only
            # - get-childitem $env:SYSTEMDRIVE\azureData azure only
            - jfrog --version
            - Get-PSDrive C
