resources:
  - name: myrepo
    type: GitRepo
    configuration:
      gitProvider: johns_github
      path: trriplejay/jfrog_samples
      branches:
        include: ^master$
        
pipelines:
  - name: powershell_example
    steps:
      - name: simple_step
        type: PowerShell
        configuration:
          inputResources:
            - name: myrepo
          nodePool: win-static
        execution:
          onExecute:
            - Write-Output "hello world!"
      - name: host_step
        type: PowerShell
        configuration:
          inputResources:
            - name: myrepo
              trigger: false
          inputSteps:
            - name: simple_step
          runtime:
            type: host
          nodePool: win-static
        execution:
          onExecute:
            - get-childitem $env:PROGRAMDATA
            - try { nssm status pipelines-seeker } catch { $_ }
            - try { nssm status pipelines-reqkick } catch { $_ }
            - cat $env:PROGRAMDATA\jfrog\pipelines\seeker\pipelines-seeker.err
            - cat $env:PROGRAMDATA\jfrog\pipelines\seeker\pipelines-seeker.out
            - get-childitem $env:SYSTEMDRIVE\azureData
