pipelines:
  - name: powershell_example
    steps:
      - name: simple_step
        type: PowerShell
        configuration:
          nodePool: win-static
        execution:
          onExecute:
            - Write-Output "hello world!"
