resources:
  - name: singleRepo_simple
    type: GitRepo
    configuration:
      gitProvider: johns_github
      path: trriplejay/jfrog_samples
      branches:
        include: master

pipelines:
  - name: simple_pipe_simple
    steps:
      - name: first_step_simple
        type: Bash
        configuration:
          inputResources:
            - name: singleRepo_simple
          runtime:
            type: image
            image:
              custom:
                name: library/ubuntu
                tag: "18.04"
        execution:
          onExecute:
            - bash --version
            - echo "pipeline source branch is - {{gitBranch}}"
            - add_run_variables "value=password123"

      - name: second_step_simple
        type: Bash
        configuration:
          inputSteps:
            - name: first_step_simple
        execution:
          onExecute:
            - echo "final step in the pipeline"
            - echo "my password is $value"


